title: Challenges
email: rhwndqja@icloud.com
description: >
  This is the kjb Jekyll Theme.
baseurl: "https://kojungbeom.com"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
background-image: url('spacex-693229.jpg')
